name: 'Maven Tests'
description: 'Execute Maven tests and generate surefire reports'

inputs:
  maven-args:
    description: 'Additional Maven arguments'
    required: false
    default: '-B'
  coverage-threshold:
    description: 'Minimum code coverage percentage'
    required: false
    default: '80'
  maven-args:
    description: 'Additional Maven arguments'
    required: false
    default: '-B'
  fail-on-threshold:
    description: 'Fail the action if coverage is below threshold'
    required: false
    default: 'true'

outputs:
  coverage-percentage:
    description: 'JaCoCo code coverage percentage'
    value: ${{ steps.coverage.outputs.percentage }}
  threshold-met:
    description: 'Whether coverage threshold was met'
    value: ${{ steps.coverage.outputs.threshold-met }}

outputs:
  tests-passed:
    description: 'Number of Maven tests passed'
    value: ${{ steps.test.outputs.passed }}
  tests-failed:
    description: 'Number of Maven tests failed'
    value: ${{ steps.test.outputs.failed }}
  tests-total:
    description: 'Total number of tests executed'
    value: ${{ steps.test.outputs.total }}

runs:
  using: 'composite'
  steps:
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Maven dependencies
      shell: bash
      run: |
        echo "☕ Installing Maven dependencies..."
        mvn dependency:resolve ${{ inputs.maven-args }} -q

    - name: Run Maven Tests
      id: test
      shell: bash
      run: |
        echo "🧪 Running Maven tests..."
        mvn clean test ${{ inputs.maven-args }}
        
        # Extract test results from surefire reports
        if [ -d "target/surefire-reports" ]; then
          PASSED=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -h 'tests=' {} \; | sed 's/.*tests="\([0-9]*\)".*/\1/' | awk '{sum+=$1} END {print sum}')
          FAILED=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -h 'failures=' {} \; | sed 's/.*failures="\([0-9]*\)".*/\1/' | awk '{sum+=$1} END {print sum}')
          TOTAL=$((${PASSED:-0} + ${FAILED:-0}))
          
          echo "passed=${PASSED:-0}" >> $GITHUB_OUTPUT
          echo "failed=${FAILED:-0}" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          
          echo "✅ Tests passed: ${PASSED:-0}, failed: ${FAILED:-0}, total: $TOTAL"
        else
          echo "⚠️ No surefire reports found"
          echo "passed=0" >> $GITHUB_OUTPUT
          echo "failed=0" >> $GITHUB_OUTPUT
          echo "total=0" >> $GITHUB_OUTPUT
        fi

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: maven-test-reports-${{ github.run_id }}
        path: |
          target/surefire-reports/
          target/test-classes/
        retention-days: 30

    - name: Publish Test Results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Maven Tests
        path: target/surefire-reports/TEST-*.xml
        reporter: java-junit
        fail-on-error: false

    - name: Generate JaCoCo Coverage Report
      id: coverage
      shell: bash
      run: |
        echo "📊 Generating JaCoCo coverage report..."
        mvn jacoco:report ${{ inputs.maven-args }}
        
        if [ -f "target/site/jacoco/index.html" ]; then
          COVERAGE=$(grep -o 'Total[^<]*[0-9]*%' target/site/jacoco/index.html | head -1 | grep -o '[0-9]*%' | tr -d '%' || echo "0")
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "📊 JaCoCo code coverage: $COVERAGE%"
          
          # Check coverage threshold
          if [ "$COVERAGE" -lt "${{ inputs.coverage-threshold }}" ]; then
            echo "threshold-met=false" >> $GITHUB_OUTPUT
            echo "❌ Coverage ($COVERAGE%) below threshold (${{ inputs.coverage-threshold }}%)"
            
            if [ "${{ inputs.fail-on-threshold }}" = "true" ]; then
              exit 1
            fi
          else
            echo "threshold-met=true" >> $GITHUB_OUTPUT
            echo "✅ Coverage ($COVERAGE%) meets threshold (${{ inputs.coverage-threshold }}%)"
          fi
        else
          echo "⚠️ JaCoCo report not found at target/site/jacoco/index.html"
          echo "percentage=0" >> $GITHUB_OUTPUT
          echo "threshold-met=false" >> $GITHUB_OUTPUT
          
          if [ "${{ inputs.fail-on-threshold }}" = "true" ]; then
            echo "❌ No coverage report found and fail-on-threshold is enabled"
            exit 1
          fi
        fi

    - name: Upload JaCoCo Coverage Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-coverage-reports-${{ github.run_id }}
        path: target/site/jacoco/
        retention-days: 30

    - name: Generate Summary
      shell: bash
      run: |
        echo "## 📊 JaCoCo Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo "- **Coverage Percentage**: ${{ steps.coverage.outputs.percentage }}%" >> $GITHUB_STEP_SUMMARY
        echo "- **Coverage Threshold**: ${{ inputs.coverage-threshold }}%" >> $GITHUB_STEP_SUMMARY
        echo "- **Threshold Met**: ${{ steps.coverage.outputs.threshold-met == 'true' && '✅ Yes' || '❌ No' }}" >> $GITHUB_STEP_SUMMARY
        echo "## 🧪 Maven Test Results" >> $GITHUB_STEP_SUMMARY
        echo "- **Tests Passed**: ${{ steps.test.outputs.passed }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Tests Failed**: ${{ steps.test.outputs.failed }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Total Tests**: ${{ steps.test.outputs.total }}" >> $GITHUB_STEP_SUMMARY
        
        # Add detailed test results if available
        if [ -d "target/surefire-reports" ]; then
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📊 Test Details" >> $GITHUB_STEP_SUMMARY
          
          # Show failed tests if any
          if [ "${{ steps.test.outputs.failed }}" -gt 0 ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### ❌ Failed Tests" >> $GITHUB_STEP_SUMMARY
            find target/surefire-reports -name "TEST-*.xml" -exec grep -l 'failures="[^0]"' {} \; | while read file; do
              TEST_CLASS=$(basename "$file" .xml | sed 's/TEST-//')
              echo "- **$TEST_CLASS**" >> $GITHUB_STEP_SUMMARY
            done
          fi
          
          # Show test execution time
          TOTAL_TIME=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -h 'time=' {} \; | sed 's/.*time="\([^"]*\)".*/\1/' | awk '{sum+=$1} END {printf "%.2f", sum}')
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "⏱️ **Total Execution Time**: ${TOTAL_TIME}s" >> $GITHUB_STEP_SUMMARY
        fi
